"""add gallery_views table

Revision ID: 7a7903619ad6
Revises: c91e9d95b740
Create Date: 2026-03-28 16:13:27.616149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a7903619ad6'
down_revision: Union[str, Sequence[str], None] = 'c91e9d95b740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gallery_views',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('gallery_id', sa.Uuid(), nullable=False),
    sa.Column('share_link_id', sa.Uuid(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gallery_id'], ['galleries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['share_link_id'], ['share_links.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gallery_views_gallery_id'), 'gallery_views', ['gallery_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gallery_views_gallery_id'), table_name='gallery_views')
    op.drop_table('gallery_views')
    # ### end Alembic commands ###
