"""add branding fields to users

Revision ID: 96f39ea3255c
Revises: 0aa81d26a382
Create Date: 2026-03-28 18:07:33.188990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96f39ea3255c'
down_revision: Union[str, Sequence[str], None] = 'e532e6704930'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('branding_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('branding_logo_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'branding_logo_url')
    op.drop_column('users', 'branding_name')
    # ### end Alembic commands ###
