"""add email_verified to users

Revision ID: c91e9d95b740
Revises: f3c7c50b03d8
Create Date: 2026-03-28 13:11:54.519098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c91e9d95b740'
down_revision: Union[str, Sequence[str], None] = 'f3c7c50b03d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'galleries', 'images', ['cover_image_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verified')
    op.drop_constraint(None, 'galleries', type_='foreignkey')
    # ### end Alembic commands ###
