"""add comments table

Revision ID: e532e6704930
Revises: 7a7903619ad6
Create Date: 2026-03-28 17:52:13.338341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e532e6704930'
down_revision: Union[str, Sequence[str], None] = '7a7903619ad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('image_id', sa.Uuid(), nullable=False),
    sa.Column('gallery_id', sa.Uuid(), nullable=False),
    sa.Column('author_name', sa.String(length=100), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['gallery_id'], ['galleries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_gallery_id'), 'comments', ['gallery_id'], unique=False)
    op.create_index(op.f('ix_comments_image_id'), 'comments', ['image_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_image_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_gallery_id'), table_name='comments')
    op.drop_table('comments')
    # ### end Alembic commands ###
